### PR TITLE
allow skipping of comment download

### PR DESCRIPTION
**Pull request by artoonie**
Makes archiving much faster when you skip all comments.

Issue link: https://github.com/aliparlakci/bulk-downloader-for-reddit/issues/791

### CODE REVIEW

**Review by qwertie64982 — APPROVED** [review]
Came right to the PRs section just for this! lgtm, running locally and it works.

**Comment by Serene-Arc** [comment]
Hi can you add tests for this? If you can't or don't know how, say so and I'll get to it when I have time.

**Comment by OMEGARAZER** [comment]
As an FYI, it looks like this PR is against the master branch instead of the dev branch.
Would probably be best to [swap it to dev](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request)

**Comment by artoonie** [comment]
Thanks! Updated to point to dev, fixed merge conflicts, and added a test.

**Pull request merged**
