### PR TITLE
Allow 2FA on script unsavedposts.py

### PR DESCRIPTION
**Pull request by andrelam**
Added the possibility to log with 2FA enabled via pyotp. Also, moved the settings to a .env file.

### CODE REVIEW

**Comment by Serene-Arc** [comment]
Hi! Thanks for the contribution. Are you comfortable writing tests for this script? I know that there aren't currently any tests for it but there's no time like the present to add some! If you're not, that's fine, just say and I'll work something out.

**Comment by andrelam** [comment]
I can try. ;)

**Comment by Serene-Arc** [comment]
Thank you!

**Comment by OMEGARAZER** [comment]
As an FYI, it looks like this PR is against the master branch instead of the dev branch.
Would probably be best to [swap it to dev](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request)

**Comment by Serene-Arc** [comment]
@OMEGARAZER and this is why we have an action protecting master lol, I got really tired of not catching this and having to reverse commits and do bad git stuff

**Comment by andrelam** [comment]
> As an FYI, it looks like this PR is against the master branch instead of the dev branch. Would probably be best to [swap it to dev](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request)

Done. I didn't catch that either.

**Comment by andrelam** [comment]
There are some differences that I need to solve between master and dev branch. I'll drop this PR and submit a new one against dev branch.

**Pull request closed without merging**
